== Skipper Server

The Skipper Server is responsible for:

* Deploying streams to one or more platforms.
+
NOTE: The default platform is a `localhost` (so in docker environment application starts as a separate JVM process).

* Upgrading and rolling back streams on one or more platforms by using a state machine-based blue/green update strategy.
* Storing the history of each stream's manifest file (which represents the final description of what applications have been deployed).


Skipper consists of a server application that exposes an HTTP API. A shell application provides easy-to-use https://docs.spring.io/spring-cloud-skipper/docs/2.11.3/reference/htmlsingle/#skipper-commands-reference[commands] to interact with the server. The server uses a relational database to store state. Documentation to call the HTTP API is available in the https://docs.spring.io/spring-cloud-skipper/docs/2.11.3/reference/htmlsingle/#api-guide[REST API Guide].;

* Locally it runs on `7577` port;
* Console init: `make skipper-shell`;
* https://docs.spring.io/spring-cloud-skipper/docs/2.11.3/reference/htmlsingle/#skipper-commands-reference[console commands]

The main https://docs.spring.io/spring-cloud-skipper/docs/2.11.3/reference/htmlsingle/#_concepts[concepts] are Platforms, Packages, Repositories, Releases, and Release Workflows:

Platforms:: are where your apps run;
Packages:: define the basic recipe for describing what to install on a platform;
Repositories:: are where package metadata and zip files are hosted. Repositories can either be 'local' or 'remote';
Releases:: are created in Skipper after you install, upgrade, or rollback a package;
+
NOTE: The default configuration of Skipper deploys apps to the local machine.

Release Workflows:: are the steps taken to upgrade or rollback an application from one version to another;

