spring:
  application:
    name: demo-processor-kafka
  cloud:
    stream:
      bindings:
        toUpperCase-in-0:
          destination: demo-data-raw
        toUpperCase-out-0:
          destination: demo-data-processed
      kafka:
        binder:
          brokers:
            - localhost:9092
