spring:
  application:
    name: demo-processor-kafka
  cloud:
    function:
      definition: toUpperCase|addStaticString
    stream:
      function:
        bindings:
          toUpperCase|addStaticString-in-0: processed-data-in
          toUpperCase|addStaticString-out-0: processed-data-out
      bindings:
        processed-data-in:
          destination: demo-data-raw
        processed-data-out:
          destination: demo-data-processed
      kafka:
        binder:
          brokers:
            - localhost:9092

