spring:
  application:
    name: demo-sink-kafka
  cloud:
    stream:
      bindings:
        messageLogger-in-0:
          destination: demo-data-processed
      kafka:
        binder:
          brokers:
            - localhost:9092
